FROM centos

MAINTAINER Vijayendra

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat
RUN cd /var/tmp
RUN curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz
RUN tar xvfz apache-tomcat-9*
RUN mv apache-tomcat-9.*/* /opt/tomcat/.
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
RUN dnf update -y
RUN dnf install  java-11 -y
RUN java -version
RUN yum install git -y
RUN yum install -y yum-utils
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
RUN yum -y install terraform

WORKDIR /opt/tomcat/webapps
RUN curl -O -L https://updates.jenkins.io/download/war/2.405/jenkins.war

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]